fx_version 'adamant'
game 'gta5'

author 'Bastien MAGAN'
description 'Framework privé'
version '1.0.0'

dependency 'xsound'

files {
    'inventory/html/*.html',
    'inventory/html/js/*.js',
    'inventory/html/css/*.css',
    'inventory/html/locales/*.js',
    'inventory/html/img/*.png',
    'inventory/html/img/items/*.png',
    'module/creatorPerso/html/*.html',
    'module/creatorPerso/html/css/*.css',
    'module/creatorPerso/html/js/*.js',
    'module/multichar/html/*.html',
    'module/creatorPerso/html/img/parents/mothers/*.png',
    'module/creatorPerso/html/img/parents/fathers/*.png',
    'module/clothshop/html/*.html',
    'module/clothshop/html/css/*.css',
    'module/clothshop/html/js/*.js',
    'module/adminmenu/html/*.html',
    'module/adminmenu/html/css/*.css',
    'module/adminmenu/html/js/*.js',
    'module/bank/html/*.html',
    'module/bank/html/css/*.css',
    'module/bank/html/js/*.js',
    'module/bank/html/js/views/*.js',
    'module/bank/html/img/*.png',
    'module/bank/html/sounds/*.mp3',
    'module/mdt/html/*.html',
    'module/mdt/html/css/*.css',
    'module/mdt/html/js/*.js',
    'module/samu/html/*.html',
    'module/samu/html/css/*.css',
    'module/samu/html/js/*.js',
    'module/police/html/*.html',
    'module/police/html/css/*.css',
    'module/police/html/js/*.js',
}

ui_page 'module/creatorPerso/html/ui.html'

-- Modèles/animations custom du menu émotes (module/emotes), repris tels
-- quels de rpemotes-reborn (github.com/alberttheprince/rpemotes-reborn)
data_file 'CONDITIONAL_ANIMS_FILE' 'emotes_conditionalanims.meta'

data_file 'DLC_ITYP_REQUEST' 'stream/rpemotesreborn_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brummie_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_camp_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/apple_1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/kaykaymods_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/knjgh_pizzas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/natty_props_lollipops.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ultra_ringcase.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pata_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vedere_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pnwsigns.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pprp_icefishing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/scully_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/samnick_prop_lighter01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_murderpack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/prop_protestsign_fh.ytyp'

client_scripts {
    'client/function.lua',
	'dependencies/RageUI/RMenu.lua',
    'dependencies/RageUI/menu/RageUI.lua',
    'dependencies/RageUI/menu/Menu.lua',
    'dependencies/RageUI/menu/MenuController.lua',
    'dependencies/RageUI/components/*.lua',
    'dependencies/RageUI/menu/elements/*.lua',
    'dependencies/RageUI/menu/items/*.lua',
    'dependencies/RageUI/menu/panels/*.lua',
    'dependencies/RageUI/menu/windows/*.lua',
    'client/callbacks.lua',
    'client/datastore.lua',
    'client/zones.lua',
    'client/richpresence.lua',
    'client/command.lua',
    'module/multichar/client/main.lua',
    'module/multichar/client/apartment.lua',
    'client/player/player.lua',
    'client/player/gunfight.lua',
    'client/player/spawn.lua',
    'client/player/pickup.lua',
    'client/player/status.lua',
    'client/player/skills.lua',
    'client/player/injury.lua',
    'client/player/point.lua',
    'client/player/arms.lua',
    'client/player/crouch.lua',
    'module/emotes/data/emotes_emotes.lua',
    'module/emotes/data/emotes_dances.lua',
    'module/emotes/data/emotes_props.lua',
    'module/emotes/data/emotes_walks.lua',
    'module/emotes/data/emotes_expressions.lua',
    'module/emotes/data/emotes_shared.lua',
    'module/emotes/data/emotes_animals.lua',
    'module/emotes/cl_emotes.lua',
    'module/emotes/cl_idlecam.lua',
    'module/emotes/cl_binoculars.lua',
    'module/emotes/cl_newscam.lua',
    'client/player/carry.lua',
    'client/player/hostage.lua',
    'inventory/utils.lua',
    'inventory/client/main.lua',
    'module/adminmenu/cl_admin.lua',
    'module/creatorPerso/client/camera.lua',
    'module/creatorPerso/client/main.lua',
    'module/creatorPerso/client/cutscene.lua',
    'module/identity/cl_identity.lua',
    'module/bank/cl_bank.lua',
    'module/bank/cl_paymentMenu.lua',
    'module/clothshop/cl_clothshop.lua',
    'module/needs/cl_needs.lua',
    'module/persistent_vehicles/cl_persistent.lua',
    'module/persistent_vehicles/cl_vehiclemenu.lua',
    'module/persistent_vehicles/cl_handbrake.lua',
    'module/persistent_vehicles/cl_stability.lua',
    'module/garage/cl_garage.lua',
    'module/pedOffline/client/main.lua',
    'module/keyhanger/client/main.lua',
    'module/keyhanger/client/placement.lua',
    'module/mdt/shared/permissions.lua',
    'module/mdt/client/main.lua',
    'module/police/client/main.lua',
    'module/police/client/actions.lua',
    'module/police/client/radio.lua',
    'module/police/client/investigation.lua',
    'module/police/client/prison.lua',
    'module/police/client/callouts.lua',
    'module/gendarmerie/client/main.lua',
    'module/samu/client/main.lua',
    'module/samu/client/actions.lua',
    'module/samu/client/health_inspection.lua',
    'module/samu/client/mdt_medical.lua',
    'module/pompiers/client/main.lua',
    'module/pompiers/client/actions.lua',
    -- module/mecanicien : remplacé par module/atelier (multi-entreprises).
    -- Conservé sur disque le temps de valider la migration, plus chargé.
    -- 'module/mecanicien/client/main.lua',
    -- 'module/mecanicien/client/actions.lua',
    -- 'module/mecanicien/client/parts.lua',
    -- 'module/mecanicien/client/tow.lua',
    'module/atelier/shared/permissions.lua',
    'module/atelier/shared/components.lua',
    'module/atelier/client/main.lua',
    'module/atelier/client/diagnostic.lua',
    'module/atelier/client/inventory.lua',
    'module/atelier/client/interventions.lua',
    'module/atelier/client/billing.lua',
    'module/metro/client/main.lua',
    'module/ltd/client/main.lua',
    'module/ltd/client/actions.lua',
    'module/concessionnaire/client/main.lua',
    'module/concessionnaire/client/showroom.lua',
    'module/concessionnaire/client/actions.lua',
    'module/fourriere/client/impound.lua',
    'module/fourriere/client/main.lua',
    'module/interim/client/main.lua',
    'module/interim/client/vehicles.lua',
    'module/interim/client/refuel.lua',
    'module/interim/client/no_spawn.lua',
    'module/pompe/client/main.lua',
    'module/farm/client/main.lua',
    'module/wildlife/client/main.lua',
    'module/sit/client/main.lua',
    'module/weather/client/main.lua',
    'client/anticheat.lua',
    'client/postalmap.lua',
}

shared_scripts {
    '@ox_lib/init.lua',
    'shared/*.lua',
    'module/multichar/config.lua',
    'module/sit/config.lua',
    'module/sit/data/actions.lua',
    'module/sit/data/models.lua',
    'module/pedOffline/config.lua',
    'module/pedOffline/languages/fr.lua',
    'module/pedOffline/class/main.lua',
    'module/keyhanger/config.lua',
    'module/keyhanger/languages/fr.lua',
    'module/mdt/config.lua',
    'module/police/config.lua',
    'module/police/config_mdt.lua',
    'module/police/config_callouts.lua',
    'module/police/shared/scenarios.lua',
    'module/police/shared/dialogues.lua',
    'module/police/languages/fr.lua',
    'module/gendarmerie/config.lua',
    'module/gendarmerie/config_mdt.lua',
    'module/gendarmerie/languages/fr.lua',
    'module/samu/config.lua',
    'module/samu/config_mdt.lua',
    'module/samu/config_medical.lua',
    'module/samu/languages/fr.lua',
    'module/pompiers/config.lua',
    'module/pompiers/config_mdt.lua',
    'module/pompiers/languages/fr.lua',
    -- 'module/mecanicien/config.lua',
    -- 'module/mecanicien/languages/fr.lua',
    'module/atelier/config/config.lua',
    'module/atelier/config/companies.lua',
    'module/atelier/config/parts.lua',
    'module/atelier/languages/fr.lua',
    'module/metro/config.lua',
    'module/metro/languages/fr.lua',
    'module/ltd/config.lua',
    'module/ltd/languages/fr.lua',
    'module/concessionnaire/config.lua',
    'module/concessionnaire/languages/fr.lua',
    'module/fourriere/config.lua',
    'module/interim/config.lua',
    'module/pompe/config.lua',
    'module/farm/config.lua',
    'module/farm/languages/fr.lua',
    'module/wildlife/config.lua',
    'module/weather/config.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'shared/shared.lua',
    'server/function.lua',
    'server/validate.lua',
    'server/callbacks.lua',
    'server/commands.lua',
    'server/zones.lua',
    'server/datastore.lua',
    'module/multichar/server/main.lua',
    'server/player/*.lua',
    'inventory/server/main.lua',
    'module/adminmenu/sv_admin.lua',
    'module/creatorPerso/server/main.lua',
    'module/identity/sv_identity.lua',
    'module/bank/sv_bank.lua',
    'module/bank/sv_paymentMenu.lua',
    'module/clothshop/sv_clothshop.lua',
    'module/needs/sv_needs.lua',
    'module/persistent_vehicles/sv_persistent.lua',
    'module/persistent_vehicles/sv_handbrake.lua',
    'module/garage/sv_garage.lua',
    'module/pedOffline/server/main.lua',
    'module/keyhanger/server/main.lua',
    'module/mdt/shared/permissions.lua',
    'module/mdt/server/main.lua',
    'module/police/server/main.lua',
    'module/police/server/actions.lua',
    'module/police/server/prison.lua',
    'module/police/server/investigation.lua',
    'module/police/server/callouts.lua',
    'module/gendarmerie/server/main.lua',
    'module/samu/server/main.lua',
    'module/samu/server/actions.lua',
    'module/samu/server/mdt_medical.lua',
    'module/pompiers/server/main.lua',
    'module/pompiers/server/actions.lua',
    -- 'module/mecanicien/server/main.lua',
    -- 'module/mecanicien/server/actions.lua',
    -- 'module/mecanicien/server/parts.lua',
    'module/atelier/shared/permissions.lua',
    'module/atelier/shared/components.lua',
    'module/atelier/server/security.lua',
    'module/atelier/server/main.lua',
    'module/atelier/server/vehicles.lua',
    'module/atelier/server/diagnostic.lua',
    'module/atelier/server/inventory.lua',
    'module/atelier/server/repairs.lua',
    'module/atelier/server/billing.lua',
    'module/metro/server/main.lua',
    'module/ltd/server/main.lua',
    'module/ltd/server/stock.lua',
    'module/concessionnaire/server/main.lua',
    'module/fourriere/server/main.lua',
    'module/interim/server/main.lua',
    'module/pompe/server/main.lua',
    'module/farm/server/main.lua',
    'module/emotes/sv_emotes.lua',
    'server/deferallsCards.lua',
    'module/sit/server/main.lua',
    'module/weather/server/main.lua',
    'server/anticheat.lua',
    'server/boutique.lua'
}