fx_version 'adamant'
game 'gta5'

author 'Bastien MAGAN'
description 'Framework privé'
version '1.0.0'

dependency 'xsound'

files {
    'inventory/html/*.html',
    'inventory/html/js/*.js',
    'inventory/html/css/*.css',
    'inventory/html/locales/*.js',
    'inventory/html/img/*.png',
    'inventory/html/img/items/*.png',
    'module/creatorperso/html/*.html',
    'module/creatorperso/html/css/*.css',
    'module/creatorperso/html/js/*.js',
    'module/multichar/html/*.html',
    'module/creatorperso/html/img/parents/mothers/*.png',
    'module/creatorperso/html/img/parents/fathers/*.png',
    'module/clothshop/html/*.html',
    'module/clothshop/html/css/*.css',
    'module/clothshop/html/js/*.js',
    'module/adminmenu/html/*.html',
    'module/adminmenu/html/css/*.css',
    'module/adminmenu/html/js/*.js',
    'module/bank/html/*.html',
    'module/bank/html/css/*.css',
    'module/bank/html/js/*.js',
    'module/bank/html/js/views/*.js',
    'module/bank/html/img/*.png',
    'module/bank/html/sounds/*.mp3',
    'module/mdt/html/*.html',
    'module/mdt/html/*.png',
    'module/mdt/html/css/*.css',
    'module/mdt/html/js/*.js',
    'module/atc/html/*.html',
    'module/atelier/html/*.html',
    'module/atelier/html/css/*.css',
    'module/atelier/html/js/*.js',
    'module/ems/html/*.html',
    'module/ems/html/css/*.css',
    'module/ems/html/js/*.js',
    'module/police/html/*.html',
    'module/police/html/css/*.css',
    'module/police/html/js/*.js',
    'module/garage/html/*.html',
    'module/garage/html/css/*.css',
    'module/garage/html/js/*.js',
}

ui_page 'module/creatorperso/html/ui.html'

-- Modèles/animations custom du menu émotes (module/emotes), repris tels
-- quels de rpemotes-reborn (github.com/alberttheprince/rpemotes-reborn)
data_file 'CONDITIONAL_ANIMS_FILE' 'emotes_conditionalanims.meta'

data_file 'DLC_ITYP_REQUEST' 'stream/rpemotesreborn_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brummie_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_camp_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/apple_1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/kaykaymods_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/knjgh_pizzas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/natty_props_lollipops.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ultra_ringcase.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pata_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vedere_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pnwsigns.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pprp_icefishing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/scully_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/samnick_prop_lighter01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_murderpack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/prop_protestsign_fh.ytyp'

client_scripts {
    'client/function.lua',
    'client/population.lua',
    'module/pnj_vehicule/client/main.lua',
	'dependencies/RageUI/RMenu.lua',
    'dependencies/RageUI/menu/RageUI.lua',
    'dependencies/RageUI/menu/Menu.lua',
    'dependencies/RageUI/menu/MenuController.lua',
    'dependencies/RageUI/components/*.lua',
    'dependencies/RageUI/menu/elements/*.lua',
    'dependencies/RageUI/menu/items/*.lua',
    'dependencies/RageUI/menu/panels/*.lua',
    'dependencies/RageUI/menu/windows/*.lua',
    'client/callbacks.lua',
    'client/datastore.lua',
    'client/zones.lua',
    'client/richpresence.lua',
    'client/command.lua',
    'module/multichar/client/main.lua',
    'module/multichar/client/apartment.lua',
    'client/player/player.lua',
    'client/player/gunfight.lua',
    'client/player/spawn.lua',
    'client/player/pickup.lua',
    'client/player/status.lua',
    'client/player/skills.lua',
    'client/player/injury.lua',
    'client/player/point.lua',
    'client/player/arms.lua',
    'client/player/crouch.lua',
    'client/player/visor.lua',
    'module/emotes/data/emotes_emotes.lua',
    'module/emotes/data/emotes_dances.lua',
    'module/emotes/data/emotes_props.lua',
    'module/emotes/data/emotes_walks.lua',
    'module/emotes/data/emotes_expressions.lua',
    'module/emotes/data/emotes_shared.lua',
    'module/emotes/data/emotes_animals.lua',
    'module/emotes/client/main.lua',
    'module/gabzmenu/data/vehicles.lua',
    'module/gabzmenu/client/main.lua',
    'module/emotes/client/idlecam.lua',
    'module/emotes/client/binoculars.lua',
    'module/emotes/client/newscam.lua',
    'client/player/carry.lua',
    'client/player/hostage.lua',
    'inventory/utils.lua',
    'inventory/client/main.lua',
    'module/adminmenu/client/main.lua',
    'module/creatorperso/client/camera.lua',
    'module/creatorperso/client/main.lua',
    'module/creatorperso/client/cutscene.lua',
    'module/identity/client/main.lua',
    'module/bank/client/main.lua',
    'module/bank/client/payment_menu.lua',
    'module/society/client/main.lua',
    'module/clothshop/client/main.lua',
    'module/needs/client/main.lua',
    'module/persistentvehicles/client/main.lua',
    'module/persistentvehicles/client/vehiclemenu.lua',
    'module/persistentvehicles/client/handbrake.lua',
    'module/persistentvehicles/client/stability.lua',
    'module/garage/client/main.lua',
    'module/garage/client/hud.lua',
    'module/garage/client/creator.lua',
    'module/atc/client/survey.lua',
    'module/atc/client/aircraft.lua',
    'module/atc/client/tower.lua',
    -- module/atc/client/props.lua désactivé : suppression props/véhicules ambiants reprise en dehors du module ATC.
    'module/atc/client/no_spawn_zones.lua',
    'module/pedoffline/client/main.lua',
    'module/keyhanger/client/main.lua',
    'module/keyhanger/client/placement.lua',
    'module/mdt/shared/permissions.lua',
    'module/mdt/client/main.lua',
    'module/mdt/client/boutique.lua',
    'module/mdt/client/parts.lua',
    'module/mdt/client/grades.lua',
    'module/police/client/main.lua',
    'module/police/client/armory.lua',
    'module/police/client/actions.lua',
    'module/police/client/investigation.lua',
    'module/police/client/prison.lua',
    'module/police/client/callouts.lua',
    'module/police/client/shootingrange.lua',
    'module/obstacles/client/placement.lua',
    'module/obstacles/client/main.lua',
    'module/sheriff/client/main.lua',
    'module/ems/client/main.lua',
    'module/ems/client/actions.lua',
    'module/ems/client/health_inspection.lua',
    'module/ems/client/mdt_medical.lua',
    'module/lsfd/client/main.lua',
    'module/lsfd/client/actions.lua',
    -- module/mecanicien : remplacé par module/atelier (multi-entreprises), supprimé.
    'module/atelier/shared/permissions.lua',
    'module/atelier/shared/components.lua',
    'module/atelier/client/main.lua',
    'module/atelier/client/diagnostic.lua',
    'module/atelier/client/inventory.lua',
    'module/atelier/client/interventions.lua',
    'module/atelier/client/billing.lua',
    'module/atelier/client/tuning.lua',
    'module/atelier/client/paintdebug.lua',
    'module/metro/client/main.lua',
    -- Module LTD (métier, caisse, stock) en suspens : seule la boutique PNJ Little Seoul reste active
    'module/ltd/client/pedshop.lua',
    'module/concessionnaire/client/main.lua',
    'module/concessionnaire/client/showroom.lua',
    'module/concessionnaire/client/actions.lua',
    'module/location/client/main.lua',
    'module/location/client/rental.lua',
    'module/fourriere/client/impound.lua',
    'module/fourriere/client/main.lua',
    'module/fourriere/client/towtruck.lua',
    'module/interim/client/main.lua',
    'module/interim/client/vehicles.lua',
    'module/interim/client/refuel.lua',
    'module/interim/client/no_spawn.lua',
    'module/pompe/client/main.lua',
    'module/gym/client/main.lua',
    'module/farm/client/main.lua',
    'module/avicole/client/main.lua',
    'module/wildlife/client/main.lua',
    'module/sit/client/main.lua',
    'module/weather/client/main.lua',
    'client/anticheat.lua',
    'client/postalmap.lua',
    'module/foodapi/client/main.lua',
    'module/ls_burgershot/client/main.lua',
    'module/ls_burgershot/client/craft.lua',
    'module/ls_burgershot/client/storage.lua',
    'module/ls_burgershot/client/cash.lua',
    'module/ls_burgershot/client/target.lua',
    'module/ls_aldentes/client/main.lua',
    'module/ls_aldentes/client/craft.lua',
    'module/ls_aldentes/client/storage.lua',
    'module/ls_aldentes/client/cash.lua',
    'module/ls_aldentes/client/target.lua',
    'module/ls_kebabking/client/main.lua',
    'module/ls_kebabking/client/craft.lua',
    'module/ls_kebabking/client/storage.lua',
    'module/ls_kebabking/client/cash.lua',
    'module/ls_kebabking/client/target.lua',
    'module/grossiste/client/main.lua',
    'module/nonlethal/client/effects.lua',
    'module/nonlethal/client/lbd.lua',
    'module/nonlethal/client/cougar.lua',
    'module/nonlethal/client/gazeuse.lua',
    'module/nonlethal/client/grenades.lua',
    'module/nonlethal/client/trainingammo.lua',
}

shared_scripts {
    '@ox_lib/init.lua',
    'shared/*.lua',
    'module/foodapi/config.lua',
    'module/multichar/config.lua',
    'module/sit/config.lua',
    'module/sit/data/actions.lua',
    'module/sit/data/models.lua',
    'module/pedoffline/config.lua',
    'module/pedoffline/languages/fr.lua',
    'module/pedoffline/class/main.lua',
    'module/keyhanger/config.lua',
    'module/keyhanger/languages/fr.lua',
    'module/mdt/config.lua',
    'module/obstacles/config.lua',
    'module/police/config.lua',
    'module/police/config_mdt.lua',
    'module/police/config_callouts.lua',
    'module/police/shared/scenarios.lua',
    'module/police/shared/dialogues.lua',
    'module/police/languages/fr.lua',
    'module/sheriff/config.lua',
    'module/sheriff/config_mdt.lua',
    'module/sheriff/languages/en.lua',
    'module/ems/config.lua',
    'module/ems/config_mdt.lua',
    'module/ems/config_medical.lua',
    'module/ems/languages/fr.lua',
    'module/lsfd/config.lua',
    'module/lsfd/config_mdt.lua',
    'module/lsfd/languages/fr.lua',
    'module/atelier/config/config.lua',
    'module/atelier/config/companies.lua',
    'module/atelier/config/parts.lua',
    'module/atelier/config/tuning.lua',
    'module/atelier/config_mdt.lua',
    'module/atelier/languages/fr.lua',
    'module/metro/config.lua',
    'module/metro/languages/fr.lua',
    'module/ltd/config.lua',
    'module/concessionnaire/config.lua',
    'module/concessionnaire/languages/fr.lua',
    'module/location/config.lua',
    'module/fourriere/config.lua',
    'module/garage/config.lua',
    'module/society/config.lua',
    'module/interim/config.lua',
    'module/avicole/config.lua',
    'module/pompe/config.lua',
    'module/gym/config.lua',
    'module/farm/config.lua',
    'module/farm/languages/fr.lua',
    'module/wildlife/config.lua',
    'module/weather/config.lua',
    'module/atc/config/config.lua',
    'module/atc/config/lsia_runways.lua',
    'module/atc/config/lsia_stands.lua',
    'module/atc/config/lsia_graph.lua',
    'module/atc/config/aircraft.lua',
    'module/atc/shared/core.lua',
    'module/ls_burgershot/config/config.lua',
    'module/ls_burgershot/config/items.lua',
    'module/ls_burgershot/config/recipes.lua',
    'module/ls_burgershot/shared/utils.lua',
    'module/ls_burgershot/config_mdt.lua',
    'module/ls_aldentes/config/config.lua',
    'module/ls_aldentes/config/items.lua',
    'module/ls_aldentes/config/recipes.lua',
    'module/ls_aldentes/shared/utils.lua',
    'module/ls_kebabking/config/config.lua',
    'module/ls_kebabking/config/items.lua',
    'module/ls_kebabking/config/recipes.lua',
    'module/ls_kebabking/shared/utils.lua',
    'module/ls_kebabking/config_mdt.lua',
    'module/grossiste/config/config.lua',
    'module/grossiste/config/items.lua',
    'module/grossiste/config/catalog.lua',
    'module/grossiste/shared/utils.lua',
    'module/nonlethal/config.lua',
    'module/pnj_vehicule/config.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'shared/shared.lua',
    'server/function.lua',
    'server/validate.lua',
    'server/callbacks.lua',
    'server/commands.lua',
    'server/zones.lua',
    'server/datastore.lua',
    'server/population.lua',
    'server/evidence.lua',
    'module/multichar/server/main.lua',
    'server/player/*.lua',
    'inventory/server/main.lua',
    'module/adminmenu/server/main.lua',
    'module/creatorperso/server/main.lua',
    'module/identity/server/main.lua',
    'module/bank/server/main.lua',
    'module/bank/server/payment_menu.lua',
    'module/society/server/main.lua',
    'module/clothshop/server/main.lua',
    'module/needs/server/main.lua',
    'module/persistentvehicles/server/main.lua',
    'module/persistentvehicles/server/handbrake.lua',
    'module/garage/server/main.lua',
    'module/pedoffline/server/main.lua',
    'module/keyhanger/server/main.lua',
    'module/pnj_vehicule/server/main.lua',
    'module/mdt/shared/permissions.lua',
    'module/mdt/server/main.lua',
    'module/mdt/server/boutique.lua',
    'module/mdt/server/parts.lua',
    'module/mdt/server/grades.lua',
    'module/police/server/main.lua',
    'module/police/server/armory.lua',
    'module/police/server/actions.lua',
    'module/police/server/prison.lua',
    'module/police/server/investigation.lua',
    'module/police/server/callouts.lua',
    'module/police/server/shootingrange.lua',
    'module/obstacles/server/main.lua',
    'module/sheriff/server/main.lua',
    'module/ems/server/main.lua',
    'module/ems/server/actions.lua',
    'module/ems/server/mdt_medical.lua',
    'module/lsfd/server/main.lua',
    'module/lsfd/server/actions.lua',
    'module/atelier/shared/permissions.lua',
    'module/atelier/shared/components.lua',
    'module/atelier/server/security.lua',
    'module/atelier/server/main.lua',
    'module/atelier/server/vehicles.lua',
    'module/atelier/server/diagnostic.lua',
    'module/atelier/server/inventory.lua',
    'module/atelier/server/repairs.lua',
    'module/atelier/server/grade_permissions.lua',
    'module/atelier/server/billing.lua',
    'module/atelier/server/tuning.lua',
    'module/metro/server/main.lua',
    'module/ltd/server/pedshop.lua',
    'module/concessionnaire/server/main.lua',
    'module/location/server/main.lua',
    'module/fourriere/server/main.lua',
    'module/interim/server/main.lua',
    'module/pompe/server/main.lua',
    'module/gym/server/main.lua',
    'module/farm/server/main.lua',
    'module/avicole/server/main.lua',
    'module/emotes/server/main.lua',
    'server/deferallsCards.lua',
    'module/sit/server/main.lua',
    'module/sit/server/edit.lua',
    'module/weather/server/main.lua',
    'module/atc/server/survey.lua',
    'module/atc/server/flights.lua',
    'server/anticheat.lua',
    'server/boutique.lua',
    'module/foodapi/server/main.lua',
    'module/ls_burgershot/server/main.lua',
    'module/ls_burgershot/server/craft.lua',
    'module/ls_burgershot/server/storage.lua',
    'module/ls_burgershot/server/cash.lua',
    'module/ls_aldentes/server/main.lua',
    'module/ls_aldentes/server/craft.lua',
    'module/ls_aldentes/server/storage.lua',
    'module/ls_aldentes/server/cash.lua',
    'module/ls_kebabking/server/main.lua',
    'module/ls_kebabking/server/craft.lua',
    'module/ls_kebabking/server/pots.lua',
    'module/ls_kebabking/server/storage.lua',
    'module/ls_kebabking/server/cash.lua',
    'module/grossiste/server/main.lua',
    'module/nonlethal/server/main.lua',
}