-- ═══════════════════════════════════════════════════════════════════
--  CONCESSIONNAIRE — Configuration principale
--  Boutique PNJ ouverte à tous — Framework : LSLegacy (custom)
--  Auteur : Bastien MAGAN
-- ═══════════════════════════════════════════════════════════════════

Config.Concessionnaire = {}

-- ── PNJ vendeur (Premium Deluxe Motorsport) ─────────────────────────
Config.Concessionnaire.Seller = {
    model   = 'a_m_y_business_01',      -- modèle du ped vendeur (achat + occasions)
    coords  = vector3(-56.33, -1098.41, 26.42),
    heading = 24.6,
}

-- ── PNJ dédié à la revente ───────────────────────────────────────────
Config.Concessionnaire.ResaleSeller = {
    model   = 'a_m_y_business_01',
    coords  = vector3(-27.68, -1091.38, 26.42),
    heading = 66.1,
}

-- ── Spot de prévisualisation (plateau d'exposition intérieur PDM) ─────
-- Le véhicule sélectionné apparaît ici pour être vu avant l'achat.
Config.Concessionnaire.Preview = {
    coords  = vector3(-46.86, -1095.6, 26.44),
    heading = 90.0,
}

-- ── Point de livraison (sortie du concessionnaire, sur la voie) ───────
Config.Concessionnaire.Delivery = {
    coords  = vector3(-30.0, -1092.6, 26.42),
    heading = 240.0,
}

-- ── Zone sans trafic PNJ (UNIQUEMENT l'intérieur du bâtiment) ─────────
-- Box couvrant l'emprise du showroom. Les véhicules ambiants qui s'y
-- trouvent sont retirés ; la rue autour n'est PAS affectée.
-- Épargnés : l'aperçu, tout véhicule "mission", tout véhicule occupé
-- par un joueur.  center = centre de la box · size = dimensions (x,y,z).
Config.Concessionnaire.NoTraffic = {
    center = vector3(-47.0, -1097.0, 26.4),
    size   = vector3(30.0, 30.0, 8.0),
}

-- ── Blip carte ───────────────────────────────────────────────────────
Config.Concessionnaire.Blip = {
    coords = vector3(-56.33, -1098.41, 26.42),
    sprite = 326,
    color  = 46,
    scale  = 0.9,
    label  = 'Concessionnaire',
    short  = true,
}

-- ── Moyens de paiement autorisés ─────────────────────────────────────
-- 'cash' = argent liquide (LSLegacy.Money) · 'bank' = compte courant
Config.Concessionnaire.Payment = {
    cash = false,
    bank = true,
}

-- ── Catalogue ────────────────────────────────────────────────────────
-- Ajoute/retire librement des catégories et des véhicules.
-- price = prix en $. model = spawn name GTA (ou addon).
Config.Concessionnaire.Catalog = {
    {
        category = 'Compactes',
        vehicles = {
            { model = 'asbo',       label = 'Maxwell Asbo',              price = 800  },
            { model = 'dilettante', label = 'Karin Dilettante',         price = 900  },
            { model = 'panto',      label = 'Benefactor Panto',         price = 1000  },
            { model = 'issi2',      label = 'Weeny Issi',               price = 1250 },
            { model = 'blista',     label = 'Dinka Blista',             price = 1350 },
            { model = 'prairie',    label = 'Bollokan Prairie',         price = 1450 },
            { model = 'rhapsody',   label = 'Declasse Rhapsody',        price = 1550 },
            { model = 'issi3',      label = 'Weeny Issi Classic',       price = 1650 },
            { model = 'brioso2',    label = 'Grotti Brioso 300',        price = 1750 },
            { model = 'club',       label = 'BF Club',                  price = 1750 },
            { model = 'kanjo',      label = 'Dinka Kanjo',              price = 1900 },
            { model = 'brioso',     label = 'Grotti Brioso R/A',        price = 2000 },
            { model = 'weevil',     label = 'BF Weevil',                price = 2100 },
            { model = 'brioso3',    label = 'Grotti Brioso 300 Widebody', price = 2200 },
        },
    },
    {
        category = 'Berlines',
        vehicles = {
            { model = 'emperor',       label = 'Albany Emperor',        price = 1200  },
            { model = 'regina',        label = 'Dundreary Regina',      price = 1400  },
            { model = 'ingot',         label = 'Vulcar Ingot',          price = 1950 },
            { model = 'primo',         label = 'Albany Primo',          price = 2350 },
            { model = 'asea',          label = 'Declasse Asea',         price = 2550 },
            { model = 'stratum',       label = 'Zirconium Stratum',     price = 2550 },
            { model = 'glendale',      label = 'Benefactor Glendale',   price = 2750 },
            { model = 'stanier',       label = 'Vapid Stanier',         price = 2750 },
            { model = 'asterope',      label = 'Karin Asterope',        price = 2900 },
            { model = 'minimus',       label = 'Vapid Minimus',         price = 3100 },
            { model = 'intruder',      label = 'Karin Intruder',        price = 3100 },
            { model = 'primo2',        label = 'Albany Primo Custom',   price = 3300 },
            { model = 'washington',    label = 'Albany Washington',     price = 3500 },
            { model = 'fugitive',      label = 'Cheval Fugitive',       price = 3700 },
            { model = 'premier',       label = 'Declasse Premier',      price = 3850 },
            { model = 'glendale2',     label = 'Benefactor Glendale Custom', price = 3850 },
            { model = 'romero',        label = 'Chariot Romero',        price = 3850 },
            { model = 'surge',         label = 'Cheval Surge',          price = 4250 },
            { model = 'warrener',      label = 'Vulcar Warrener',       price = 4650 },
            { model = 'warrener2',     label = 'Vulcar Warrener HKR',   price = 5000 },
            { model = 'tailgater',     label = 'Obey Tailgater',        price = 5000 },
            { model = 'asterope2',     label = 'Karin Asterope GT',     price = 5400 },
            { model = 'schafter2',     label = 'Benefactor Schafter',   price = 5800 },
            { model = 'drifthardy',    label = 'Vapid Hardy (Drift)',   price = 7700 },
            { model = 'driftchavosv6', label = 'Vapid Chavos V6 (Drift)', price = 8250 },
            { model = 'stafford',      label = 'Enus Stafford',         price = 8250 },
            { model = 'cinquemila',    label = 'Lampadati Cinquemila',  price = 8850 },
            { model = 'rhinehart',     label = 'Enus Rhinehart',        price = 10750 },
            { model = 'cognoscenti',   label = 'Enus Cognoscenti',      price = 11150 },
            { model = 'cog55',         label = 'Enus Cognoscenti 55',   price = 11500 },
            { model = 'deity',         label = 'Enus Deity',            price = 13050 },
            { model = 'superd',        label = 'Enus Super Diamond',    price = 14000 },
        },
    },
    {
        category = 'SUV',
        vehicles = {
            { model = 'mesa',        label = 'Canis Mesa',              price = 1800 },
            { model = 'habanero',    label = 'Emperor Habanero',        price = 2350 },
            { model = 'bjxl',        label = 'BeeJay XL',               price = 2350 },
            { model = 'radi',        label = 'Vapid Radius',            price = 2950 },
            { model = 'gresley',     label = 'Bravado Gresley',         price = 2950 },
            { model = 'seminole',    label = 'Canis Seminole',          price = 2950 },
            { model = 'rocoto',      label = 'Obey Rocoto',             price = 3500 },
            { model = 'fq2',         label = 'Fathom FQ 2',             price = 4100 },
            { model = 'landstalker', label = 'Dundreary Landstalker',   price = 4100 },
            { model = 'serrano',     label = 'Benefactor Serrano',      price = 4100 },
            { model = 'seminole2',   label = 'Canis Seminole Frontier', price = 4650 },
            { model = 'granger',     label = 'Declasse Granger',        price = 4650 },
            { model = 'cavalcade',   label = 'Albany Cavalcade',        price = 5550 },
            { model = 'dubsta',      label = 'Benefactor Dubsta',       price = 6400 },
            { model = 'contender',   label = 'Vapid Contender',         price = 6950 },
            { model = 'baller',      label = 'Gallivanter Baller',      price = 6950 },
            { model = 'squaddie',    label = 'Bravado Squaddie',        price = 6950 },
            { model = 'dubsta2',     label = 'Benefactor Dubsta 2',     price = 6950 },
            { model = 'issi8',       label = 'Weeny Issi Rallye',       price = 6950 },
            { model = 'woodlander',  label = 'Vapid Woodlander',        price = 7550 },
            { model = 'aleutian',    label = 'Vapid Aleutian',          price = 7550 },
            { model = 'cavalcade2',  label = 'Albany Cavalcade 2',      price = 7550 },
            { model = 'landstalker2',label = 'Dundreary Landstalker XL',price = 7550 },
            { model = 'baller2',     label = 'Gallivanter Baller LE',   price = 8400 },
            { model = 'granger2',    label = 'Declasse Granger 3600LX', price = 8400 },
            { model = 'patriot',     label = 'Mammoth Patriot',         price = 8400 },
            { model = 'dorado',      label = 'Vapid Dorado',            price = 8400 },
            { model = 'cavalcade3',  label = 'Albany Cavalcade (new)',  price = 9250 },
            { model = 'xls',         label = 'Benefactor XLS',          price = 9250 },
            { model = 'baller3',     label = 'Gallivanter Baller LE LWB', price = 9850 },
            { model = 'huntley',     label = 'Enus Huntley S',          price = 9850 },
            { model = 'baller4',     label = 'Gallivanter Baller LE LWB', price = 10400 },
            { model = 'rebla',       label = 'Übermacht Rebla GTS',     price = 10400 },
            { model = 'novak',       label = 'Lampadati Novak',         price = 11250 },
            { model = 'baller6',     label = 'Gallivanter Baller ST',   price = 11250 },
            { model = 'vivanite',    label = 'Vysser Vivanite',         price = 11250 },
            { model = 'everon3',     label = 'Karin Everon',            price = 11250 },
            { model = 'iwagen',      label = 'Obey I-Wagen',            price = 12700 },
            { model = 'baller7',     label = 'Gallivanter Baller ST-D', price = 12700 },
            { model = 'toros',       label = 'Pegassi Toros',           price = 14150 },
            { model = 'astron',      label = 'Pfister Astron',          price = 15550 },
            { model = 'jubilee',     label = 'Enus Jubilee',            price = 17000 },
        },
    },
    {
        category = 'Coupés',
        vehicles = {
            { model = 'oracle',    label = 'Übermacht Oracle',       price = 2200 },
            { model = 'sentinel',  label = 'Übermacht Sentinel',     price = 2200 },
            { model = 'oracle2',   label = 'Übermacht Oracle XS',    price = 3000 },
            { model = 'sentinel2', label = 'Übermacht Sentinel XS',  price = 3000 },
            { model = 'kanjosj',   label = 'Dinka Kanjo SJ',         price = 4150 },
            { model = 'zion',      label = 'Übermacht Zion',         price = 4150 },
            { model = 'jackal',    label = 'Ocelot Jackal',          price = 5350 },
            { model = 'zion2',     label = 'Übermacht Zion Cabrio',  price = 5350 },
            { model = 'felon',     label = 'Lampadati Felon',        price = 6150 },
            { model = 'felon2',    label = 'Lampadati Felon GT',     price = 6950 },
            { model = 'f620',      label = 'Ocelot F620',            price = 6950 },
            { model = 'previon',   label = 'Karin Previon',          price = 6950 },
            { model = 'sentinel6', label = 'Übermacht Sentinel Classic', price = 8100 },
            { model = 'exemplar',  label = 'Dewbauchee Exemplar',    price = 8100 },
            { model = 'postlude',  label = 'Dinka Postlude',         price = 10100 },
            { model = 'fr36',      label = 'Ocelot FR36',            price = 12050 },
            { model = 'windsor',   label = 'Enus Windsor',           price = 12050 },
            { model = 'windsor2',  label = 'Enus Windsor Drop',      price = 13250 },
            { model = 'cogcabrio', label = 'Enus Cognoscenti Cabrio', price = 16000 },
        },
    },
    {
        category = 'Muscle Car',
        vehicles = {
            { model = 'ratloader2', label = 'Bravado Rat-Truck',       price = 4600 },
            { model = 'voodoo2',    label = 'Declasse Voodoo (beater)',price = 1200 },
            { model = 'voodoo',     label = 'Declasse Voodoo',         price = 7400 },
            { model = 'chino',      label = 'Vapid Chino',             price = 7400 },
            { model = 'vigero',     label = 'Declasse Vigero',         price = 7950 },
            { model = 'blade',      label = 'Vapid Blade',             price = 7950 },
            { model = 'picador',    label = 'Cheval Picador',          price = 7950 },
            { model = 'slamvan',    label = 'Vapid Slamvan',           price = 7950 },
            { model = 'ruiner',     label = 'Imponte Ruiner',          price = 7950 },
            { model = 'buccaneer',  label = 'Albany Buccaneer',        price = 8500 },
            { model = 'dukes',      label = 'Imponte Dukes',           price = 8500 },
            { model = 'phoenix',    label = 'Imponte Phoenix',         price = 8500 },
            { model = 'faction',    label = 'Willard Faction',         price = 8500 },
            { model = 'sabregt',    label = 'Declasse Sabre Turbo',    price = 8500 },
            { model = 'stalion',    label = 'Declasse Stallion',       price = 8500 },
            { model = 'tampa',      label = 'Declasse Tampa',          price = 8500 },
            { model = 'virgo',      label = 'Albany Virgo',            price = 8500 },
            { model = 'broadway',   label = 'Classique Broadway',      price = 9350 },
            { model = 'gauntlet',   label = 'Bravado Gauntlet',        price = 9350 },
            { model = 'dominator',  label = 'Vapid Dominator',         price = 9350 },
            { model = 'impaler',    label = 'Declasse Impaler',        price = 9350 },
            { model = 'clique',     label = 'Vapid Clique',            price = 9350 },
            { model = 'manana2',    label = 'Lampadati Manana Custom', price = 9350 },
            -- Lowriders (customs hydrauliques)
            { model = 'virgo3',     label = 'Albany Virgo Classic',       price = 9100 },
            { model = 'chino2',     label = 'Vapid Chino Custom',         price = 9350 },
            { model = 'slamvan3',   label = 'Vapid Slamvan Custom',       price = 9350 },
            { model = 'buccaneer2', label = 'Albany Buccaneer Custom',    price = 9650 },
            { model = 'faction2',   label = 'Willard Faction Custom',     price = 9650 },
            { model = 'sabregt2',   label = 'Declasse Sabre Turbo Custom',price = 9650 },
            { model = 'virgo2',     label = 'Albany Virgo Classic Custom',price = 9650 },
            { model = 'hermes',     label = 'Albany Hermes',           price = 10200 },
            { model = 'ellie',      label = 'Vapid Ellie',             price = 10200 },
            { model = 'deviant',    label = 'Schyster Deviant',        price = 10200 },
            { model = 'vamos',      label = 'Declasse Vamos',          price = 10200 },
            { model = 'tulip',      label = 'Declasse Tulip',          price = 10200 },
            { model = 'lurcher',    label = 'Bravado Lurcher',         price = 10800 },
            { model = 'eudora',     label = 'Willard Eudora',          price = 10800 },
            { model = 'brigham',    label = 'Albany Brigham',          price = 10800 },
            { model = 'yosemite',   label = 'Declasse Yosemite',       price = 10800 },
            { model = 'tahoma',     label = 'Declasse Tahoma Coupe',   price = 10800 },
            { model = 'gauntlet3',  label = 'Bravado Gauntlet Classic',price = 10800 },
            { model = 'greenwood',  label = 'Bravado Greenwood',       price = 11350 },
            { model = 'faction3',   label = 'Willard Faction Donk',    price = 11350 },
            { model = 'nightshade', label = 'Imponte Nightshade',      price = 11350 },
            { model = 'hustler',    label = 'Vapid Hustler',           price = 11350 },
            { model = 'coquette3',  label = 'Invetero Coquette BlackFin', price = 12200 },
            { model = 'hotknife',   label = 'Vapid Hotknife',          price = 12200 },
            { model = 'gauntlet5',  label = 'Bravado Gauntlet Classic Custom', price = 12200 },
            { model = 'dominator3', label = 'Vapid Dominator GTX',     price = 12200 },
            { model = 'vigero3',    label = 'Declasse Vigero ZX',      price = 12200 },
            { model = 'dominator7', label = 'Vapid Dominator ASP',     price = 13600 },
            { model = 'dominator8', label = 'Vapid Dominator GT',      price = 14150 },
            { model = 'dominator9', label = 'Vapid Dominator',         price = 15000 },
        },
    },
    {
        category = 'Sportives classique',
        vehicles = {
            { model = 'cheburek',   label = 'Cheval Cheburek',            price = 2500 },
            { model = 'tornado3',   label = 'Declasse Tornado Rat Rod',   price = 3500 },
            { model = 'tornado5',   label = 'Declasse Tornado (rouillée)', price = 3500 },
            { model = 'tornado',    label = 'Declasse Tornado',           price = 5800 },
            { model = 'tornado2',   label = 'Declasse Tornado Cabriolet', price = 5800 },
            { model = 'peyote',     label = 'Vapid Peyote',               price = 6500 },
            { model = 'manana',     label = 'Albany Manana',              price = 6800 },
            { model = 'tornado4',   label = 'Declasse Tornado Custom',    price = 7150 },
            { model = 'tornado6',   label = 'Declasse Tornado Custom II', price = 7150 },
            { model = 'peyote3',    label = "Vapid Peyote '73",           price = 7150 },
            { model = 'fagaloa',    label = 'Vulcar Fagaloa',             price = 7800 },
            { model = 'retinue',    label = 'Vapid Retinue',              price = 8450 },
            { model = 'nebula',     label = 'Vulcar Nebula Turbo',        price = 8450 },
            { model = 'dynasty',    label = 'Weeny Dynasty',              price = 9150 },
            { model = 'pigalle',    label = 'Lampadati Pigalle',          price = 11800 },
            { model = 'retinue2',   label = 'Vapid Retinue MkII',         price = 11800 },
            { model = 'zion3',      label = 'Übermacht Zion Classic',     price = 13450 },
            { model = 'michelli',   label = 'Lampadati Michelli GT',      price = 13450 },
            { model = 'savestra',   label = 'Annis Savestra',             price = 13450 },
            { model = 'swinger',    label = 'Ocelot Swinger',             price = 16750 },
            { model = 'mamba',      label = 'Declasse Mamba',             price = 18400 },
            { model = 'ardent',     label = 'Ocelot Ardent',              price = 18400 },
            { model = 'itali2',     label = 'Lampadati Casco II',         price = 18400 },
            { model = 'astrale',    label = 'Lampadati Astrale',          price = 19050 },
            { model = 'rapidgt3',   label = 'Dewbauchee Rapid GT Classic', price = 20050 },
            { model = 'z190',       label = 'Ocelot Locust',              price = 20050 },
            { model = 'viseris',    label = 'Grotti Viseris',             price = 20050 },
            { model = 'gt750',      label = 'Ocelot GT750',               price = 21700 },
            { model = 'casco',      label = 'Lampadati Casco',            price = 21700 },
            { model = 'btype2',     label = 'Albany Franken Stange',      price = 21700 },
            { model = 'coquette2',  label = 'Invetero Coquette Classic',  price = 21700 },
            { model = 'monroe',     label = 'Pegassi Monroe',             price = 21700 },
            { model = 'btype',      label = 'Albany Roosevelt',           price = 23350 },
            { model = 'stinger',    label = 'Grotti Stinger',             price = 23350 },
            { model = 'feltzer3',   label = 'Benefactor Stirling GT',     price = 23350 },
            { model = 'gt500',      label = 'Grotti GT500',               price = 24350 },
            { model = 'stingergt',  label = 'Grotti Stinger GT',          price = 25050 },
            { model = 'btype3',     label = 'Albany Roosevelt Valor',     price = 25050 },
            { model = 'cheetah2',   label = 'Grotti Cheetah Classic',     price = 90000 },
            { model = 'torero',     label = 'Pegassi Torero',             price = 26700 },
            { model = 'infernus2',  label = 'Pegassi Infernus Classic',   price = 110000 },
            { model = 'turismo2',   label = 'Grotti Turismo Classic',     price = 150000 },
            { model = 'ztype',      label = 'Truffade Z-Type',            price = 130000 },
        },
    },
    {
        category = 'Sportives',
        vehicles = {
            { model = 'futo',        label = 'Karin Futo',                 price = 3000 },
            { model = 'fusilade',    label = 'Schyster Fusilade',          price = 8950 },
            { model = 'futo2',       label = 'Karin Futo GTX',             price = 8950 },
            { model = 'penumbra',    label = 'Maibatsu Penumbra',          price = 10150 },
            { model = 'alpha',       label = 'Albany Alpha',               price = 11950 },
            { model = 'buffalo',     label = 'Bravado Buffalo',            price = 11950 },
            { model = 'buffalo2',    label = 'Bravado Buffalo S',          price = 13750 },
            { model = 'tropos',      label = 'Lampadati Tropos Rallye',    price = 13750 },
            { model = 'elegy',       label = 'Annis Elegy RH8',            price = 14950 },
            { model = 'schwarzer',   label = 'Benefactor Schwartzer',      price = 14950 },
            { model = 'remus',       label = 'Annis Remus',                price = 16150 },
            { model = 'surano',      label = 'Benefactor Surano',          price = 16150 },
            { model = 'khamelion',   label = 'Hijak Khamelion',            price = 17900 },
            { model = 'sultan',      label = 'Karin Sultan',               price = 17900 },
            { model = 'bestiagts',   label = 'Grotti Bestia GTS',          price = 17900 },
            { model = 'omnis',       label = 'Obey Omnis',                 price = 17900 },
            { model = 'penumbra2',   label = 'Maibatsu Penumbra FF',       price = 17900 },
            { model = 'rapidgt',     label = 'Dewbauchee Rapid GT',        price = 17900 },
            { model = 'elegy2',      label = 'Annis Elegy Retro Custom',   price = 17900 },
            { model = 'sentinel3',   label = 'Übermacht Sentinel Classic', price = 17900 },
            { model = 'sugoi',       label = 'Dinka Sugoi',                price = 17900 },
            { model = 'sentinel4',   label = 'Übermacht Sentinel',         price = 18500 },
            { model = 'sentinel5',   label = 'Übermacht Sentinel XS',      price = 18500 },
            { model = 'schafter3',   label = 'Benefactor Schafter LWB',    price = 19700 },
            { model = 'rapidgt2',    label = 'Dewbauchee Rapid GT Cabrio', price = 19700 },
            { model = 'banshee',     label = 'Bravado Banshee',            price = 20900 },
            { model = 'coquette',    label = 'Invetero Coquette',          price = 20900 },
            { model = 'issi7',       label = 'Weeny Issi Sport',           price = 20900 },
            { model = 'lynx',        label = 'Ocelot Lynx',                price = 20900 },
            { model = 'ninef',       label = 'Obey 9F',                    price = 20900 },
            { model = 'sultan2',     label = 'Karin Sultan RS Classic',    price = 20900 },
            { model = 'verlierer2',  label = 'Bravado Verlierer',          price = 20900 },
            { model = 'rapidgt4',    label = 'Dewbauchee Rapid GT Widebody', price = 20900 },
            { model = 'feltzer2',    label = 'Benefactor Feltzer',         price = 22100 },
            { model = 'calico',      label = 'Karin Calico GTF',           price = 22100 },
            { model = 'kuruma',      label = 'Karin Kuruma',               price = 22100 },
            { model = 'ninef2',      label = 'Obey 9F Cabrio',             price = 22100 },
            { model = 'raptor',      label = 'BF Raptor',                  price = 22100 },
            { model = 'sultan3',     label = 'Karin Sultan RS',            price = 22100 },
            { model = 'gb200',       label = 'Vapid GB200',                price = 22100 },
            { model = 'coureur',     label = 'Annis Coureur',              price = 22100 },
            { model = 'furoregt',    label = 'Lampadati Furore GT',        price = 23300 },
            { model = 'comet2',      label = 'Pfister Comet',              price = 23900 },
            { model = 'euros',       label = 'Annis Euros',                price = 23900 },
            { model = 'jester',      label = 'Dinka Jester',               price = 23900 },
            { model = 'flashgt',     label = 'Vysser Flash GT',            price = 24500 },
            { model = 'komoda',      label = 'Lampadati Komoda',           price = 24500 },
            { model = 'revolter',    label = 'Übermacht Revolter',         price = 24500 },
            { model = 'seven70',     label = 'Dewbauchee Seven-70',        price = 24500 },
            { model = 'vstr',        label = 'Albany V-STR',               price = 24500 },
            { model = 'carbonizzare', label = 'Grotti Carbonizzare',       price = 25700 },
            { model = 'drafter',     label = 'Obey 8F Drafter',            price = 25700 },
            { model = 'jugular',     label = 'Ocelot Jugular',             price = 25700 },
            { model = 'ruston',      label = 'Hijak Ruston',               price = 25700 },
            { model = 'zr350',       label = 'Annis ZR350',                price = 25700 },
            { model = 'comet3',      label = 'Pfister Comet Retro Custom', price = 26850 },
            { model = 'growler',     label = 'Pfister Growler',            price = 26850 },
            { model = 'locust',      label = 'Ocelot Locust',              price = 26850 },
            { model = 'neon',        label = 'Pfister Neon',               price = 26850 },
            { model = 'specter',     label = 'Dewbauchee Specter',         price = 26850 },
            { model = 'jester3',     label = 'Dinka Jester Classic',       price = 26850 },
            { model = 'cypher',      label = 'Übermacht Cypher',           price = 28050 },
            { model = 'jester4',     label = 'Dinka Jester RR',            price = 28050 },
            { model = 'massacro',    label = 'Dewbauchee Massacro',        price = 28050 },
            { model = 'paragon',     label = 'Enus Paragon R',             price = 29250 },
            { model = 'tenf',        label = 'Obey Tailgater 10F',         price = 29250 },
            { model = 'vectre',      label = 'Emperor Vectre',             price = 29250 },
            { model = 'comet5',      label = 'Pfister Comet SR',           price = 29850 },
            { model = 'comet6',      label = 'Pfister Comet S2',           price = 30450 },
            { model = 'tenf2',       label = 'Obey 10F Widebody',          price = 30450 },
            { model = 'comet7',      label = 'Pfister Comet S2 Cabrio',    price = 31650 },
            { model = 'imorgon',     label = 'Overflod Imorgon',           price = 31650 },
            { model = 'omnisegt',    label = 'Obey Omnis e-GT',            price = 31650 },
            { model = 'raiden',      label = 'Coil Raiden',                price = 31650 },
            { model = 'everon2',     label = 'Karin S95',                  price = 31650 },
            { model = 'neo',         label = 'Übermacht Neo',              price = 32850 },
            { model = 'panthere',    label = 'Toundra Panthere',           price = 34050 },
            { model = 'schlagen',    label = 'Benefactor Schlagen GT',     price = 35250 },
            { model = 'pariah',      label = 'Ocelot Pariah',              price = 35800 },
            { model = 'italigto',    label = 'Progen Itali GTO',           price = 37600 },
            { model = 'corsita',     label = 'Lampadati Corsita',          price = 38800 },
            { model = 'sm722',       label = 'Benefactor SM722',           price = 38800 },
            { model = 'italirsx',    label = 'Progen Itali RSX',           price = 40000 },
        },
    },
    {
        category = 'Super',
        vehicles = {
            { model = 'sultanrs',   label = 'Karin Sultan RS',            price = 120000 },
            { model = 'infernus',   label = 'Pegassi Infernus',           price = 145000 },
            { model = 'voltic',     label = 'Coil Voltic',                price = 145000 },
            { model = 'suzume',     label = 'Karin Suzume',               price = 148000 },
            { model = 'cheetah',    label = 'Grotti Cheetah',             price = 150000 },
            { model = 'penetrator', label = 'Ocelot Penetrator',          price = 150000 },
            { model = 'vacca',      label = 'Pegassi Vacca',              price = 155000 },
            { model = 'bullet',     label = 'Vapid Bullet',               price = 155000 },
            { model = 'banshee2',   label = 'Bravado Banshee 900R',       price = 160000 },
            { model = 'italigtb',   label = 'Progen Itali GTB',           price = 162000 },
            { model = 'champion',   label = 'Dewbauchee Champion',        price = 165000 },
            { model = 'tigon',      label = 'Lampadati Tigon',            price = 165000 },
            { model = 'furia',      label = 'Grotti Furia',               price = 170000 },
            { model = 'nero',       label = 'Truffade Nero',              price = 175000 },
            { model = 'thrax',      label = 'Progen Thrax',               price = 178000 },
            { model = 's80',        label = 'Ocelot S80RR',               price = 180000 },
            { model = 'turismor',   label = 'Grotti Turismo R',           price = 182000 },
            { model = 'entityxf',   label = 'Overflod Entity XF',         price = 185000 },
            { model = 'zorrusso',   label = 'Lampadati Zorrusso',         price = 188000 },
            { model = 'nero2',      label = 'Truffade Nero Custom',       price = 190000 },
            { model = 'luiva',      label = 'Vysser Luiva',               price = 190000 },
            { model = 'torero2',    label = 'Pegassi Torero XO',          price = 195000 },
            { model = 'turismo3',   label = 'Grotti Turismo Omaggio',     price = 198000 },
            { model = 'sheava',     label = 'Emperor ETR1',               price = 200000 },
            { model = 'italigtb2',  label = 'Progen Itali GTB Custom',    price = 205000 },
            { model = 'entity2',    label = 'Overflod Entity XXR',        price = 205000 },
            { model = 'lm87',       label = 'Benefactor LM87',            price = 208000 },
            { model = 'entity3',    label = 'Overflod Entity MT',         price = 210000 },
            { model = 'osiris',     label = 'Pegassi Osiris',             price = 210000 },
            { model = 'tyrant',     label = 'Overflod Tyrant',            price = 210000 },
            { model = 'fmj',        label = 'Vapid FMJ',                  price = 215000 },
            { model = 'tempesta',   label = 'Pegassi Tempesta',           price = 218000 },
            { model = 'sc1',        label = 'Übermacht SC1',              price = 220000 },
            { model = 'pfister811', label = 'Pfister 811',                price = 222000 },
            { model = 't20',        label = 'Progen T20',                 price = 225000 },
            { model = 'fmj2',       label = 'Vapid FMJ MK V',             price = 228000 },
            { model = 'prototipo',  label = 'Progen X80 Proto',           price = 230000 },
            { model = 'taipan',     label = 'Cheval Taipan',              price = 232000 },
            { model = 'virtue',     label = 'Ocelot Virtue',              price = 235000 },
            { model = 'ignus',      label = 'Pegassi Ignus',              price = 238000 },
            { model = 'xa21',       label = 'Vapid XA-21',                price = 240000 },
            { model = 'xtreme',     label = 'Vapid X-treme',              price = 242000 },
            { model = 'tyrus',      label = 'Progen Tyrus',               price = 245000 },
            { model = 'visione',    label = 'Pegassi Visione',            price = 248000 },
            { model = 'reaper',     label = 'Pegassi Reaper',             price = 250000 },
            { model = 'gp1',        label = 'Progen GP1',                 price = 252000 },
            { model = 'zeno',       label = 'Övis Zeno',                  price = 255000 },
            { model = 'krieger',    label = 'Benefactor Krieger',         price = 260000 },
            { model = 'vigilante',  label = 'Bravado Vigilante',          price = 260000 },
            { model = 'voltic2',    label = 'Coil Rocket Voltic',         price = 280000 },
            { model = 'emerus',     label = 'Progen Emerus',              price = 290000 },
            { model = 'le7b',       label = 'Annis RE-7B',                price = 300000 },
            { model = 'vagner',     label = 'Pegassi Vagner',             price = 320000 },
            { model = 'autarch',    label = 'Overflod Autarch',           price = 330000 },
            { model = 'adder',      label = 'Truffade Adder',             price = 350000 },
            { model = 'zentorno',   label = 'Pegassi Zentorno',           price = 370000 },
            { model = 'deveste',    label = 'Grotti Deveste Eight',       price = 390000 },
            { model = 'cyclone',    label = 'Coil Cyclone',               price = 420000 },
            { model = 'scramjet',   label = 'Declasse Scramjet',          price = 450000 },
            { model = 'tezeract',   label = 'Överflöd Tezeract',          price = 480000 },
        },
    },
    {
        category = 'Motos',
        vehicles = {
            { model = 'faggio',     label = 'Pegassi Faggio Sport',       price = 700   },
            { model = 'faggio2',    label = 'Pegassi Faggio',             price = 700   },
            { model = 'faggio3',    label = 'Pegassi Faggio Mod',         price = 850   },
            { model = 'avarus',     label = 'LCC Avarus',                 price = 1150   },
            { model = 'esskey',     label = 'Nagasaki Esskey',            price = 1000   },
            { model = 'manchez',    label = 'Maibatsu Manchez',           price = 1300   },
            { model = 'blazer',     label = 'Nagasaki Blazer',            price = 1550   },
            { model = 'manchez2',   label = 'Maibatsu Manchez Scout',     price = 1550   },
            { model = 'manchez3',   label = 'Maibatsu Manchez Scout C',   price = 1700   },
            { model = 'sanchez',    label = 'Maibatsu Sanchez Livery',    price = 1700   },
            { model = 'sanchez2',   label = 'Maibatsu Sanchez',           price = 1800   },
            { model = 'enduro',     label = 'Dinka Enduro',               price = 1550   },
            { model = 'gargoyle',   label = 'Nagasaki Gargoyle',          price = 2000  },
            { model = 'blazer5',    label = 'Nagasaki Blazer Aqua',       price = 2450  },
            { model = 'zombiea',    label = 'Nagasaki Zombie Bobber',     price = 2450  },
            { model = 'ratbike',    label = 'Western Rat Bike',           price = 2150  },
            { model = 'zombieb',    label = 'Western Zombie Chopper',     price = 2850  },
            { model = 'daemon',     label = 'Western Daemon',             price = 2750  },
            { model = 'daemon2',    label = 'Western Daemon Custom',      price = 3150  },
            { model = 'bagger',     label = 'Western Bagger',             price = 3300  },
            { model = 'hexer',      label = 'LCC Hexer',                  price = 3450  },
            { model = 'sovereign',  label = 'Western Sovereign',          price = 3600  },
            { model = 'wolfsbane',  label = 'Western Wolfsbane',          price = 3750  },
            { model = 'innovation', label = 'Dinka Innovation',           price = 3900  },
            { model = 'nightblade', label = 'Western Nightblade',         price = 4050  },
            { model = 'vader',      label = 'Shitzu Vader',               price = 4200  },
            { model = 'double',     label = 'Dinka Double-T',             price = 4750  },
            { model = 'lectro',     label = 'Principe Lectro',            price = 5050  },
            { model = 'akuma',      label = 'Dinka Akuma',                price = 5050  },
            { model = 'nemesis',    label = 'Principe Nemesis',           price = 5350  },
            { model = 'diablous',   label = 'Nagasaki Diabolus',          price = 5900  },
            { model = 'diablous2',  label = 'Nagasaki Diabolus Custom',   price = 6500  },
            { model = 'ruffian',    label = 'Pegassi Ruffian',            price = 6500  },
            { model = 'fcr',        label = 'Nagasaki FCR 1000',          price = 6800  },
            { model = 'vindicator', label = 'Dinka Vindicator',           price = 6950  },
            { model = 'bf400',      label = 'Nagasaki BF400',             price = 7050  },
            { model = 'fcr2',       label = 'Nagasaki FCR 1000 Custom',   price = 7350  },
            { model = 'stryder',    label = 'Nagasaki Stryder',           price = 7350  },
            { model = 'bati',       label = 'Pegassi Bati 801',           price = 7650  },
            { model = 'thrust',     label = 'Dinka Thrust',               price = 7650  },
            { model = 'hakuchou',   label = 'Shitzu Hakuchou',            price = 7950  },
            { model = 'hakuchou2',  label = 'Shitzu Hakuchou Drag',       price = 8500  },
            { model = 'defiler',    label = 'Shitzu Defiler',             price = 8500  },
            { model = 'bati2',      label = 'Pegassi Bati 801RR',         price = 8800  },
            { model = 'cliffhanger',label = 'Nagasaki Cliffhanger',       price = 8800  },
            { model = 'shinobi',    label = 'Nagasaki Shinobi',           price = 8800  },
            { model = 'carbonrs',   label = 'Nagasaki Carbon RS',         price = 9100  },
            { model = 'chimera',    label = 'Nagasaki Chimera',           price = 9400  },
            { model = 'sanctus',    label = 'LCC Sanctus',                price = 9950  },
            { model = 'reever',     label = 'Western Reever',             price = 12000  },
        },
    },
    {
        category = 'Tout-terrain',
        vehicles = {
            { model = 'dune',        label = 'BF Dune Buggy',              price = 1800 },
            { model = 'bifta',       label = 'BF Bifta',                   price = 2200 },
            { model = 'kalahari',    label = 'Canis Kalahari',             price = 2800 },
            { model = 'bfinjection', label = 'BF Injection',               price = 3200 },
            { model = 'dloader',     label = 'Bravado Duneloader',         price = 3600 },
            { model = 'boor',        label = 'Karin Boor',                 price = 3800 },
            { model = 'vagrant',     label = 'Maxwell Vagrant',            price = 4250 },
            { model = 'bodhi2',      label = 'Canis Bodhi',                price = 4850 },
            { model = 'rebel',       label = 'Karin Rusty Rebel',          price = 4850 },
            { model = 'rancherxl',   label = 'Declasse Rancher XL',        price = 5250 },
            { model = 'l352',        label = 'Vapid Walton L35 Stock',     price = 5450 },
            { model = 'rancherxl2',  label = 'Declasse Rancher XL Custom', price = 5650 },
            { model = 'l35',         label = 'Vapid Walton L35',           price = 5850 },
            { model = 'yosemite3',   label = 'Declasse Yosemite Rancher',  price = 6050 },
            { model = 'winky',       label = 'Vapid Winky',                price = 6450 },
            { model = 'mesa3',       label = 'Canis Mesa',                 price = 6850 },
            { model = 'rebel2',      label = 'Karin Rebel',                price = 7250 },
            { model = 'verus',       label = 'Dinka Verus',                price = 7650 },
            { model = 'sandking2',   label = 'Vapid Sandking SWB',         price = 8100 },
            { model = 'sandking',    label = 'Vapid Sandking XL',          price = 8500 },
            { model = 'brawler',     label = 'Vapid Brawler',              price = 8900 },
            { model = 'hellion',     label = 'Nagasaki Hellion',           price = 9300 },
            { model = 'outlaw',      label = 'Nagasaki Outlaw',            price = 9700 },
            { model = 'riata',       label = 'Vapid Riata',                price = 10100 },
            { model = 'kamacho',     label = 'Canis Kamacho',              price = 10500 },
            { model = 'caracara2',   label = 'Vapid Caracara 4x4',         price = 10900 },
            { model = 'terminus',    label = 'Fathom Terminus',            price = 11300 },
            { model = 'draugur',     label = 'Übermacht Draugur',          price = 12550 },
            { model = 'freecrawler', label = 'Canis Freecrawler',          price = 13350 },
            { model = 'ratel',       label = 'Vapid Ratel',                price = 14550 },
            { model = 'trophytruck', label = 'Vapid Trophy Truck',         price = 17000 },
            { model = 'trophytruck2',label = 'Vapid Desert Raid',          price = 18000 },
        },
    },
    {
        category = 'Vans',
        vehicles = {
            { model = 'burrito3',  label = 'Declasse Burrito',           price = 900  },
            { model = 'youga',     label = 'Bravado Youga',              price = 900  },
            { model = 'minivan',   label = 'Vapid Minivan',              price = 1000  },
            { model = 'bobcatxl',  label = 'Vapid Bobcat XL',            price = 1050  },
            { model = 'journey',   label = 'Zirconium Journey',          price = 1050  },
            { model = 'journey2',  label = 'Zirconium Journey II',       price = 1150  },
            { model = 'surfer',    label = 'BF Surfer',                  price = 1150  },
            { model = 'rumpo',     label = 'Bravado Rumpo',              price = 1200 },
            { model = 'minivan2',  label = 'Vapid Minivan Custom',       price = 2000 },
            { model = 'paradise',  label = 'Bravado Paradise',           price = 2150 },
            { model = 'moonbeam',  label = 'Declasse Moonbeam',          price = 2300 },
            { model = 'youga2',    label = 'Bravado Youga Classic',      price = 2450 },
            { model = 'moonbeam2', label = 'Declasse Moonbeam Custom',   price = 2600 },
            { model = 'youga3',    label = 'Bravado Youga Classic 4x4',  price = 2750 },
            { model = 'surfer3',   label = 'BF Surfer Custom',           price = 2750 },
            { model = 'bison',     label = 'Bravado Bison',              price = 3100 },
            { model = 'gburrito2', label = 'Declasse Burrito Custom',    price = 3400 },
            { model = 'rumpo3',    label = 'Bravado Rumpo Custom',       price = 3700 },
            { model = 'pony',      label = 'Brute Pony',                 price = 4000 },
            { model = 'taco',      label = 'Brute Taco Truck',           price = 5900 },
            { model = 'boxville6', label = 'Brute Boxville',             price = 6200 },
            { model = 'mule2',     label = 'Maibatsu Mule',              price = 6650 },
            { model = 'youga4',    label = 'Bravado Youga Custom',       price = 9000 },
        },
    },
}

-- ── Remise d'une clé à l'achat (module keyhanger) ────────────────────
Config.Concessionnaire.GiveKey = true

-- ── Plaque personnalisée (payante) ───────────────────────────────────
Config.Concessionnaire.CustomPlate = {
    enabled   = true,
    price     = 5000,       -- surcoût pour une plaque personnalisée
    maxLength = 8,          -- plaques GTA : 8 caractères max
}

-- ── Choix de couleur avant achat ─────────────────────────────────────
-- Repeindre (choisir une couleur) coûte PaintPrice. La couleur d'origine
-- (véhicule neuf ou couleur de l'occasion) reste gratuite.
Config.Concessionnaire.PaintPrice = 1000

-- id = index couleur GTA (SetVehicleColours).
Config.Concessionnaire.Colors = {
    { label = 'Noir',    id = 0   },
    { label = 'Gris',    id = 4   },
    { label = 'Argent',  id = 5   },
    { label = 'Blanc',   id = 111 },
    { label = 'Rouge',   id = 27  },
    { label = 'Bleu',    id = 64  },
    { label = 'Bleu ciel', id = 70 },
    { label = 'Vert',    id = 53  },
    { label = 'Jaune',   id = 88  },
    { label = 'Orange',  id = 38  },
    { label = 'Violet',  id = 71  },
    { label = 'Or',      id = 90  },
}

-- ── Essai (test-drive) ───────────────────────────────────────────────
Config.Concessionnaire.TestDrive = {
    enabled        = true,
    duration       = 60,                             -- secondes
    spawn          = vector4(-20.0, -1084.0, 26.6, 300.0),
    boundaryCenter = vector3(-47.0, -1097.0, 26.4),  -- centre de la zone autorisée
    boundaryRadius = 500.0,                           -- au-delà : essai interrompu
}

-- ── Revente au concessionnaire (reprise) ─────────────────────────────
Config.Concessionnaire.Resale = {
    enabled = true,
    rate    = 0.6,   -- reprise à 60 % du prix catalogue
    -- Remboursement : 'bank' (compte courant) ou 'cash' (liquide)
    refundTo = 'bank',
}

-- ── Marché de l'occasion ─────────────────────────────────────────────
-- Les véhicules repris (revente) repartent en vente d'occasion.
Config.Concessionnaire.Occasion = {
    enabled = true,
    rate    = 0.8,   -- prix d'occasion = 80 % du prix neuf catalogue
}

-- ── Notification (même système que les autres modules) ────────────────
